/**
 * The test vectors in `server/GAMES-2048-FOODCROSS.md`, and the code that makes them.
 *
 * `node server/domain/engines/vectors.ts` prints the three JSON blocks the
 * document carries. They are **generated by running the engines**, never
 * written by hand, and `verify.ts` reads them back out of the document and
 * replays every one — so the document cannot drift from the code without a
 * failing check, and a Dart port that reproduces every vector reproduces the
 * engine.
 *
 * The move lists are chosen by fixed, boring policies driven from a *separate*
 * mulberry32 stream (the "policy seed"), so regenerating them gives the same
 * vectors byte for byte. The policy is not part of the contract — only the
 * resulting `moves` are.
 */
import { CONFIG } from '../../config.ts';
import { mulberry32 } from './prng.ts';
import {
  canMove,
  performance2048,
  replay2048,
  slide,
  start2048,
  SWIPES,
  type Params2048,
  type Swipe,
} from './game2048.ts';
import {
  legalSwaps,
  performanceFoodCross,
  playSwap,
  replayFoodCross,
  startFoodCross,
  type ParamsFoodCross,
} from './foodcross.ts';

export const PARAMS_2048: Params2048 = {
  size: CONFIG.games.game2048.size,
  fourOneIn: CONFIG.games.game2048.fourOneIn,
  startTiles: CONFIG.games.game2048.startTiles,
  maxMoves: CONFIG.games.game2048.maxMoves,
};

export const PARAMS_FOOD: ParamsFoodCross = {
  rows: CONFIG.games.foodCross.rows,
  cols: CONFIG.games.foodCross.cols,
  kinds: CONFIG.games.foodCross.kinds,
  moves: CONFIG.games.foodCross.moves,
  target: CONFIG.games.foodCross.target,
  tilePoints: CONFIG.games.foodCross.tilePoints,
  runMultiplier: [...CONFIG.games.foodCross.runMultiplier],
  cascadeCap: CONFIG.games.foodCross.cascadeCap,
};

export interface PrngVector {
  seed: number;
  u32: number[];
  /** `pick(n)` for n = 2, 6, 10, 16, 64 — five fresh draws after the `u32` ones. */
  picks: Array<{ n: number; value: number }>;
}

export interface Vector2048 {
  name: string;
  seed: number;
  moves: string;
  /** The opening board, before any move. */
  start: number[];
  board: number[];
  score: number;
  highestTile: number;
  over: boolean;
  performance: number;
  draws: number;
  /** The running score after each move — only on vectors of 100 moves or fewer. */
  trace?: number[];
}

export interface VectorFoodCross {
  name: string;
  seed: number;
  moves: Array<[number, number, number]>;
  start: number[];
  board: number[];
  score: number;
  reshuffles: number;
  bestCascade: number;
  performance: number;
  draws: number;
  /** The running score after each swap, so a port can find the first swap it disagrees on. */
  trace: number[];
}

export interface RejectVector {
  game: 'game_2048' | 'food_cross';
  seed: number;
  moves: string | Array<[number, number, number]>;
  reason: string;
  move: number;
}

export function prngVectors(): PrngVector[] {
  return [0, 1, 42, 2026, 0xdeadbeef, 4294967295].map((seed) => {
    const rng = mulberry32(seed);
    const u32 = [0, 1, 2, 3, 4].map(() => rng.nextU32());
    const picks = [2, 6, 10, 16, 64].map((n) => ({ n, value: rng.pick(n) }));
    return { seed, u32, picks };
  });
}

/**
 * Play 2048 with a policy: `corner` tries D, L, R, U in that order and takes the
 * first that changes the board (a decent human strategy that reaches 256–1024);
 * `random` picks uniformly among the swipes that change it. Stops at `limit`
 * moves or when the board is over.
 */
function play2048(
  seed: number,
  policy: 'corner' | 'random' | 'greedy',
  policySeed: number,
  limit: number,
): string {
  const { board } = start2048(seed, PARAMS_2048);
  const choose = mulberry32(policySeed);
  const moves: Swipe[] = [];
  /* The replay is re-run from scratch rather than stepped here, so this can
     only ever emit a list the real replay accepts. */
  let live = [...board];
  while (moves.length < limit && canMove(live, PARAMS_2048.size)) {
    const legal = SWIPES.filter((swipe) => slide([...live], PARAMS_2048.size, swipe).changed);
    if (legal.length === 0) break;
    const order: Swipe[] = ['D', 'L', 'R', 'U'];
    let swipe: Swipe;
    if (policy === 'corner') swipe = order.find((s) => legal.includes(s))!;
    else if (policy === 'random') swipe = legal[choose.pick(legal.length)];
    else {
      /* `greedy`: most empty cells after the swipe, then most merged, then the
         bottom-right tile, with `U` heavily discouraged; ties go D, L, R, U. */
      let best = Number.NEGATIVE_INFINITY;
      swipe = legal[0];
      for (const s of order) {
        if (!legal.includes(s)) continue;
        const trial = [...live];
        const { gained } = slide(trial, PARAMS_2048.size, s);
        const value =
          trial.filter((v) => v === 0).length * 1000 + gained + trial[trial.length - 1] - (s === 'U' ? 5000 : 0);
        if (value > best) {
          best = value;
          swipe = s;
        }
      }
    }
    moves.push(swipe);
    live = replay2048(seed, moves, PARAMS_2048).board;
  }
  return moves.join('');
}

function vector2048(name: string, seed: number, moves: string): Vector2048 {
  const r = replay2048(seed, [...moves] as Swipe[], PARAMS_2048);
  return {
    name,
    seed,
    moves,
    start: start2048(seed, PARAMS_2048).board,
    board: r.board,
    score: r.score,
    highestTile: r.highestTile,
    over: r.over,
    performance: performance2048(r.highestTile, CONFIG.games.game2048.performanceByTile),
    draws: r.draws,
    ...(moves.length > 0 && moves.length <= 100
      ? { trace: [...moves].map((_, i) => replay2048(seed, [...moves.slice(0, i + 1)] as Swipe[], PARAMS_2048).score) }
      : {}),
  };
}

export function vectors2048(): Vector2048[] {
  return [
    vector2048('opening board only', 1, ''),
    vector2048('three swipes', 42, play2048(42, 'random', 7, 3)),
    vector2048('twenty random swipes', 2026, play2048(2026, 'random', 11, 20)),
    vector2048('a hundred random swipes', 0xdeadbeef, play2048(0xdeadbeef, 'random', 13, 100)),
    vector2048('corner strategy to the end', 7, play2048(7, 'corner', 0, 5000)),
    vector2048('greedy to the end (reaches 512)', 3, play2048(3, 'greedy', 0, 5000)),
    vector2048('greedy to the end (reaches 1024)', 114, play2048(114, 'greedy', 0, 5000)),
    vector2048('corner strategy, 300 swipes', 4294967295, play2048(4294967295, 'corner', 0, 300)),
    vector2048('random to the end', 99, play2048(99, 'random', 17, 5000)),
  ];
}

/**
 * Play Food Cross with a policy: `greedy` takes the legal swap whose own match
 * is longest, preferring the lowest row (a sensible human habit); `random`
 * picks uniformly among legal swaps. Choices use only the board as it stands —
 * never the future refill.
 */
function playFood(seed: number, policy: 'greedy' | 'random', policySeed: number, limit: number) {
  const { board, rng } = startFoodCross(seed, PARAMS_FOOD);
  const choose = mulberry32(policySeed);
  const moves: Array<[number, number, number]> = [];
  for (let m = 0; m < limit; m += 1) {
    const legal = legalSwaps(board, PARAMS_FOOD);
    if (legal.length === 0) break;
    let pick = legal[choose.pick(legal.length)];
    if (policy === 'greedy') {
      let best = -1;
      for (const s of legal) {
        const trial = [...board];
        const a = s.row * PARAMS_FOOD.cols + s.col;
        const b = s.dir === 0 ? a + 1 : a + PARAMS_FOOD.cols;
        [trial[a], trial[b]] = [trial[b], trial[a]];
        let len = 0;
        for (const cell of [a, b]) {
          const v = trial[cell];
          const r = Math.floor(cell / PARAMS_FOOD.cols);
          const c = cell % PARAMS_FOOD.cols;
          let lo = c;
          while (lo > 0 && trial[r * PARAMS_FOOD.cols + lo - 1] === v) lo -= 1;
          let hi = c;
          while (hi < PARAMS_FOOD.cols - 1 && trial[r * PARAMS_FOOD.cols + hi + 1] === v) hi += 1;
          if (hi - lo + 1 >= 3) len = Math.max(len, hi - lo + 1);
          let up = r;
          while (up > 0 && trial[(up - 1) * PARAMS_FOOD.cols + c] === v) up -= 1;
          let dn = r;
          while (dn < PARAMS_FOOD.rows - 1 && trial[(dn + 1) * PARAMS_FOOD.cols + c] === v) dn += 1;
          if (dn - up + 1 >= 3) len = Math.max(len, dn - up + 1);
        }
        const value = len * 100 + Math.max(s.row, s.dir === 1 ? s.row + 1 : s.row);
        if (value > best) {
          best = value;
          pick = s;
        }
      }
    }
    moves.push([pick.row, pick.col, pick.dir]);
    playSwap(board, rng, pick, PARAMS_FOOD);
  }
  return moves;
}

function vectorFood(name: string, seed: number, moves: Array<[number, number, number]>): VectorFoodCross {
  const r = replayFoodCross(seed, moves.map(([row, col, dir]) => ({ row, col, dir: dir as 0 | 1 })), PARAMS_FOOD);
  return {
    name,
    seed,
    moves,
    start: startFoodCross(seed, PARAMS_FOOD).board,
    board: r.board,
    score: r.score,
    reshuffles: r.reshuffles,
    bestCascade: r.bestCascade,
    performance: performanceFoodCross(r.score, PARAMS_FOOD.target),
    draws: r.draws,
    trace: moves.map(
      (_, i) =>
        replayFoodCross(
          seed,
          moves.slice(0, i + 1).map(([row, col, dir]) => ({ row, col, dir: dir as 0 | 1 })),
          PARAMS_FOOD,
        ).score,
    ),
  };
}

export function vectorsFoodCross(): VectorFoodCross[] {
  return [
    vectorFood('opening board only', 1, []),
    vectorFood('one swap', 42, playFood(42, 'random', 3, 1)),
    vectorFood('five random swaps', 2026, playFood(2026, 'random', 5, 5)),
    vectorFood('twenty random swaps', 0xdeadbeef, playFood(0xdeadbeef, 'random', 9, 20)),
    vectorFood('twenty greedy swaps', 7, playFood(7, 'greedy', 0, 20)),
    vectorFood('twenty greedy swaps', 123456789, playFood(123456789, 'greedy', 0, 20)),
    vectorFood('twenty greedy swaps', 4294967295, playFood(4294967295, 'greedy', 0, 20)),
    vectorFood('twenty random swaps', 99, playFood(99, 'random', 21, 20)),
    vectorFood('twenty random swaps, one reshuffle on the way', 4, playFood(4, 'random', 4, 20)),
  ];
}

/** Move lists the replay must refuse, with the index and reason it must name. */
export function rejectVectors(): RejectVector[] {
  /* 2048: the opening board of seed 1, swiped in a direction that cannot move
     it, is found by trying all four. */
  let stuck: { seed: number; swipe: Swipe } | null = null;
  for (let seed = 1; seed < 1000 && !stuck; seed += 1) {
    const opening = start2048(seed, PARAMS_2048).board;
    const swipe = SWIPES.find((s) => !slide([...opening], PARAMS_2048.size, s).changed);
    if (swipe) stuck = { seed, swipe };
  }
  const good = vectors2048()[1];
  const food = vectorsFoodCross()[2];
  /* Food Cross: the first swap on the opening board of seed 42 that exchanges two
     *different* tiles and makes no match. */
  const board = startFoodCross(42, PARAMS_FOOD).board;
  const legal = legalSwaps([...board], PARAMS_FOOD).map((s) => `${s.row},${s.col},${s.dir}`);
  let dead: [number, number, number] = [0, 0, 0];
  outer: for (let row = 0; row < PARAMS_FOOD.rows; row += 1) {
    for (let col = 0; col < PARAMS_FOOD.cols - 1; col += 1) {
      const a = row * PARAMS_FOOD.cols + col;
      if (board[a] !== board[a + 1] && !legal.includes(`${row},${col},0`)) {
        dead = [row, col, 0];
        break outer;
      }
    }
  }
  const out: RejectVector[] = [
    { game: 'game_2048', seed: 42, moves: `${good.moves}X`, reason: 'bad_move', move: good.moves.length },
    { game: 'food_cross', seed: 42, moves: [dead], reason: 'no_match', move: 0 },
    { game: 'food_cross', seed: 2026, moves: [...food.moves, [7, 7, 0]], reason: 'bad_move', move: food.moves.length },
    { game: 'food_cross', seed: 2026, moves: [[0, 0, 2]], reason: 'bad_move', move: 0 },
  ];
  if (stuck) out.unshift({ game: 'game_2048', seed: stuck.seed, moves: stuck.swipe, reason: 'no_change', move: 0 });
  const full = vectors2048()[4];
  if (full.over) {
    out.push({ game: 'game_2048', seed: full.seed, moves: `${full.moves}L`, reason: 'no_change', move: full.moves.length });
  }
  return out;
}

/* Run directly: print the blocks the document embeds, one vector per line. */
if (/engines[\\/]vectors\.ts$/.test(process.argv[1] ?? '')) {
  const out = {
    prng: prngVectors(),
    game2048: vectors2048(),
    foodCross: vectorsFoodCross(),
    rejects: rejectVectors(),
  };
  const fence = '```';
  for (const [key, value] of Object.entries(out)) {
    const body = (value as unknown[]).map((v) => `  ${JSON.stringify(v)}`).join(',\n');
    console.log(`<!-- vectors:${key} -->\n${fence}json\n[\n${body}\n]\n${fence}\n`);
  }
}
